name: Build and Upload to Server

on:
  push:
    branches:
      - dev

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js v10
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: amplion.eu
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: /amplion.eu/sub/dev